version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10.11
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python manage.py makemigrations
      - python manage.py migrate
  build:
    commands:
      - python manage.py collectstatic --noinput
artifacts:
  files:
    - '**/*'
