version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Pre-build phase
  build:
    commands:
      - echo Build phase
      - chmod +x init_db.sh
      - ./init_db.sh
  post_build:
    commands:
      - echo Post-build phase

env:
  secrets-manager:
    DATABASE_URL: prod/DATABASE_URL:DATABASE_URL
