version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build started
  build:
    commands:
      - if [[ $STAGE == "prepare_db" ]]; then
          export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-central-1:211125541723:secret:prod/DATABASE_URL-aCWqmI --query SecretString --output text | jq -r ".database_url");
          python manage.py migrate;
          python manage.py collectstatic --noinput;
        else
          echo Build started;
        fi
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  discard-paths: yes
