version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build started
  build:
    commands:
      - if [[ $STAGE == "prepare_db" ]]; then
          python manage.py migrate;
          python manage.py collectstatic --noinput;
        else
          echo Build started;
        fi
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  discard-paths: yes
