# render.yaml
services:
  - type: web
    name: unky-rick
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn unky_rick.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: unky_rick.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: unky-rick-database
          property: connectionString

databases:
  - name: unky-rick-database
    plan: free
    properties:
      databaseName: unky_rick_db