# render.yaml
services:
  - type: web
    name: unky-rick
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    healthCheckPath: "/health_check/"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: unky_rick.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: unky-rick-database
          property: connectionString

databases:
  - name: unky-rick-database
    plan: free
    properties:
      databaseName: unky_rick_db

- type: cron
    name: scheduler
    schedule: "*/5 * * * *"
    command: "python manage.py analyze_platform\scheduler.py"