# Generated by Django 4.2 on 2024-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
         migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('column1', models.CharField(max_length=50)),
                ('column2', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
